name: Deploy to EC2

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.206.172.13 '
          cd /home/ubuntu/medusa_demo || git clone https://github.com/SAARA213/medusa_demo.git /home/ubuntu/medusa_demo
          cd /home/ubuntu/medusa_demo
          git pull
          docker-compose down
          docker-compose up -d --build
          '    
