name: Deploy to EC2

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.206.172.13 '
          # Navigate to the app directory
          cd /home/ubuntu/my-medusa_demo &&
          
          # Pull the latest code
          git pull origin main &&

          # Step 3: Install PM2 globally if it's not already installed
          sudo npm install pm2@latest -g &&
          
          # Reinstall dependencies if needed
          npm install &&
          
          # Ensure PostgreSQL is running
          sudo systemctl start postgresql &&
          
          # Run migrations if required
          npx medusa migrations run &&
          
          # Build and restart the Medusa app
          npm run build &&
          pm2 restart medusa-app || pm2 start npm --name 'medusa-app' -- start
          "
          '    
